apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - networkpolicy.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: openshift-health-api-config
    literals:
      - SERVICE_NAME=openshift-health-api
      - SERVICE_VERSION=0.3.0
      - LOG_LEVEL=INFO
      - MIN_FREE_DISK_MB=64
      - DEPENDENCY_TIMEOUT_SECONDS=1
      - POSTGRES_CHECK_ENABLED=false
      - REDIS_CHECK_ENABLED=false
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: openshift-health-api
      app.kubernetes.io/version: 0.3.0
      app.kubernetes.io/part-of: platform-health
